markdown: rdiscount
pygments: true
lsi: false
future: false
exclude: ["src", "config.rb", "README.textile", "update.sh"]

# auto: true
# safe:        false
# server:      false
# server_port: 4000

# source:      .
# destination: ./_site
# plugins:     ./_plugins

# permalink:   date

# maruku:
# use_tex:    false
# use_divs:   false
# png_engine: blahtex
# png_dir:    images/latex
# png_url:    /images/latex

# rdiscount:
# extensions: []
